name: task_management_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0  # SQLite database support
  path_provider: ^2.1.5 # Manage file paths for SQLite
  provider: ^6.1.2 # State management
  flutter_local_notifications: ^18.0.0 # Local notifications
  intl: ^0.19.0 # Date/time formatting
  csv: ^6.0.0 # Use the latest version
  pdf: ^3.11.1 # Use the latest version
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
 

  